openapi: 3.0.1
info:
  title: Selling Partner API for Sellers
  description: "The Selling Partner API for Sellers lets you retrieve information\
    \ on behalf of sellers about their seller account, such as the marketplaces they\
    \ participate in. Along with listing the marketplaces that a seller can sell in,\
    \ the API also provides additional information about the marketplace such as the\
    \ default language and the default currency. The API also provides seller-specific\
    \ information such as whether the seller has suspended listings in that marketplace."
  contact:
    name: Selling Partner API Developer Support
    url: https://sellercentral.amazon.com/gp/mws/contactus.html
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: v1
servers:
- url: https://sellingpartnerapi-na.amazon.com/
paths:
  /sellers/v1/marketplaceParticipations:
    get:
      tags:
      - sellers
      description: |-
        Returns a list of marketplaces that the seller submitting the request can sell in and information about the seller's participation in those marketplaces.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 0.016 | 15 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
      operationId: getMarketplaceParticipations
      responses:
        "200":
          description: Marketplace participations successfully retrieved.
          headers:
            x-amzn-RequestId:
              description: unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
            payload:
              example:
              - marketplace:
                  id: ATVPDKIKX0DER
                  name: Amazon.com
                  countryCode: US
                  defaultCurrencyCode: USD
                  defaultLanguageCode: en_US
                  domainName: www.amazon.com
                participation:
                  isParticipating: true
                  hasSuspendedListings: false
          x-amzn-api-sandbox:
            static:
            - request:
                parameters: {}
              response:
                payload:
                - marketplace:
                    id: ATVPDKIKX0DER
                    countryCode: US
                    name: Amazon.com
                    defaultCurrencyCode: USD
                    defaultLanguageCode: en_US
                    domainName: www.amazon.com
                  participation:
                    isParticipating: true
                    hasSuspendedListings: false
        "400":
          description: Request has missing or invalid parameters and cannot be parsed.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "403":
          description: "403 can be caused for reasons like Access Denied, Unauthorized,\
            \ Expired Token, Invalid Signature or Resource Not Found."
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "404":
          description: The resource specified does not exist.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "413":
          description: The request size exceeded the maximum accepted size.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "415":
          description: The entity of the request is in a format not supported by the
            requested resource.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "429":
          description: The frequency of requests was greater than allowed.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "500":
          description: Encountered an unexpected condition which prevented the server
            from fulfilling the request.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
        "503":
          description: Temporary overloading or maintenance of the server.
          headers:
            x-amzn-RequestId:
              description: Unique request reference id.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketplaceParticipationsResponse'
components:
  schemas:
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: An error code that identifies the type of error that occured.
        message:
          type: string
          description: A message that describes the error condition in a human-readable
            form.
        details:
          type: string
          description: Additional details that can help the caller understand or fix
            the issue.
      description: Error response returned when the request is unsuccessful.
      example:
        code: code
        details: details
        message: message
    ErrorList:
      type: array
      description: A list of error responses returned when a request is unsuccessful.
      items:
        $ref: '#/components/schemas/Error'
      x-schema-name: ErrorList
    MarketplaceParticipation:
      required:
      - marketplace
      - participation
      type: object
      properties:
        marketplace:
          $ref: '#/components/schemas/Marketplace'
        participation:
          $ref: '#/components/schemas/Participation'
      example:
        participation:
          isParticipating: true
          hasSuspendedListings: true
        marketplace:
          countryCode: countryCode
          domainName: domainName
          name: name
          defaultCurrencyCode: defaultCurrencyCode
          defaultLanguageCode: defaultLanguageCode
          id: id
    MarketplaceParticipationList:
      type: array
      description: List of marketplace participations.
      items:
        $ref: '#/components/schemas/MarketplaceParticipation'
      x-schema-name: MarketplaceParticipationList
    GetMarketplaceParticipationsResponse:
      type: object
      properties:
        payload:
          $ref: '#/components/schemas/MarketplaceParticipationList'
        errors:
          $ref: '#/components/schemas/ErrorList'
      description: The response schema for the getMarketplaceParticipations operation.
      example:
        payload:
        - participation:
            isParticipating: true
            hasSuspendedListings: true
          marketplace:
            countryCode: countryCode
            domainName: domainName
            name: name
            defaultCurrencyCode: defaultCurrencyCode
            defaultLanguageCode: defaultLanguageCode
            id: id
        - participation:
            isParticipating: true
            hasSuspendedListings: true
          marketplace:
            countryCode: countryCode
            domainName: domainName
            name: name
            defaultCurrencyCode: defaultCurrencyCode
            defaultLanguageCode: defaultLanguageCode
            id: id
        errors:
        - code: code
          details: details
          message: message
        - code: code
          details: details
          message: message
    Marketplace:
      required:
      - countryCode
      - defaultCurrencyCode
      - defaultLanguageCode
      - domainName
      - id
      - name
      type: object
      properties:
        id:
          type: string
          description: The encrypted marketplace value.
        name:
          type: string
          description: Marketplace name.
        countryCode:
          pattern: "^([A-Z]{2})$"
          type: string
          description: The ISO 3166-1 alpha-2 format country code of the marketplace.
        defaultCurrencyCode:
          type: string
          description: The ISO 4217 format currency code of the marketplace.
        defaultLanguageCode:
          type: string
          description: The ISO 639-1 format language code of the marketplace.
        domainName:
          type: string
          description: The domain name of the marketplace.
      description: Detailed information about an Amazon market where a seller can
        list items for sale and customers can view and purchase items.
      example:
        countryCode: countryCode
        domainName: domainName
        name: name
        defaultCurrencyCode: defaultCurrencyCode
        defaultLanguageCode: defaultLanguageCode
        id: id
    Participation:
      required:
      - hasSuspendedListings
      - isParticipating
      type: object
      properties:
        isParticipating:
          type: boolean
        hasSuspendedListings:
          type: boolean
          description: "Specifies if the seller has suspended listings. True if the\
            \ seller Listing Status is set to Inactive, otherwise False."
      description: Detailed information that is specific to a seller in a Marketplace.
      example:
        isParticipating: true
        hasSuspendedListings: true
x-original-swagger-version: "2.0"
