openapi: 3.0.1
info:
  title: Selling Partner API for Direct Fulfillment Transaction Status
  description: The Selling Partner API for Direct Fulfillment Transaction Status provides
    programmatic access to a direct fulfillment vendor's transaction status.
  contact:
    name: Selling Partner API Developer Support
    url: https://sellercentral.amazon.com/gp/mws/contactus.html
  license:
    name: Apache License 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 2021-12-28
servers:
- url: https://sellingpartnerapi-na.amazon.com/
paths:
  /vendor/directFulfillment/transactions/2021-12-28/transactions/{transactionId}:
    get:
      tags:
      - vendorTransaction
      description: |-
        Returns the status of the transaction indicated by the specified transactionId.

        **Usage Plan:**

        | Rate (requests per second) | Burst |
        | ---- | ---- |
        | 10 | 10 |

        The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values then those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](doc:usage-plans-and-rate-limits-in-the-sp-api).
      operationId: getTransactionStatus
      parameters:
      - name: transactionId
        in: path
        description: Previously returned in the response to the POST request of a
          specific transaction.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Success.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionStatus'
              example:
                transactionStatus:
                  transactionId: 20190108091302-6ca0ac50-d06e-45f5-a1e2-eb448eadac50
                  status: Processing
        "400":
          description: Request has missing or invalid parameters and cannot be parsed.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        "401":
          description: The request's Authorization header is not formatted correctly
            or does not contain a valid token.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: "Indicates that access to the resource is forbidden. Possible\
            \ reasons include Access Denied, Unauthorized, Expired Token, or Invalid\
            \ Signature."
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: The resource specified does not exist.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: Your rate limit (requests per second) for this operation.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "415":
          description: The request payload is in an unsupported format.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "429":
          description: The frequency of requests was greater than allowed.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: An unexpected condition occurred that prevented the server
            from fulfilling the request.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "503":
          description: Temporary overloading or maintenance of the server.
          headers:
            x-amzn-RequestId:
              description: Unique request reference identifier.
              style: simple
              explode: false
              schema:
                type: string
            x-amzn-RateLimit-Limit:
              description: |-
                Your rate limit (requests per second) for this operation.
                _Note:_ For this status code, the rate limit header is deprecated and no longer returned.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    x-amzn-api-sandbox:
      dynamic: {}
components:
  schemas:
    TransactionStatus:
      type: object
      properties:
        transactionStatus:
          $ref: '#/components/schemas/Transaction'
      description: The payload for the getTransactionStatus operation.
      example:
        transactionStatus:
          transactionId: transactionId
          errors:
            errors:
            - code: code
              details: details
              message: message
            - code: code
              details: details
              message: message
          status: Failure
    Transaction:
      required:
      - status
      - transactionId
      type: object
      properties:
        transactionId:
          type: string
          description: The unique identifier sent in the 'transactionId' field in
            response to the post request of a specific transaction.
        status:
          type: string
          description: Current processing status of the transaction.
          enum:
          - Failure
          - Processing
          - Success
          x-docgen-enum-table-extension:
          - value: Failure
            description: Transaction has failed.
          - value: Processing
            description: Transaction is in process.
          - value: Success
            description: Transaction has completed successfully.
        errors:
          $ref: '#/components/schemas/ErrorList'
      description: The transaction status details.
      example:
        transactionId: transactionId
        errors:
          errors:
          - code: code
            details: details
            message: message
          - code: code
            details: details
            message: message
        status: Failure
    ErrorList:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      description: A list of error responses returned when a request is unsuccessful.
      example:
        errors:
        - code: code
          details: details
          message: message
        - code: code
          details: details
          message: message
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: string
          description: An error code that identifies the type of error that occurred.
        message:
          type: string
          description: A message that describes the error condition.
        details:
          type: string
          description: Additional details that can help the caller understand or fix
            the issue.
      description: Error response returned when the request is unsuccessful.
      example:
        code: code
        details: details
        message: message
x-original-swagger-version: "2.0"
